name: Deploy to Github Pages

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JupyterBook cache
        uses: actions/cache@v4
        with:
          path: regridding-ecosystem-overview/_build

      - name: Setup environment
        uses: prefix-dev/setup-pixi@v0.8.2
        with:
          cache: true
          activate-environment: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Build JupyterBook
        run: |
          jupyter-book build . --warningiserror --keep-going --builder html

      - name: Dump Build Logs
        if: always()
        run: |
          find regridding-ecosystem-overview/_build/html/reports \
              -name "*.log" \
              -exec sh -c 'echo "logs from: $(basename {})\n———————————————————"; cat "{}"' \;

      - name: Upload Built Page
        if: github.event_name == "pull_request"
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: regridding-ecosystem-overview/_build/html

      - name: Upload Pages Artifact
        if: github.event_name == "push"
        uses: actions/upload-pages-artifact@v3
        with:
          path: regridding-ecosystem-overview/_build/html
          name: preview

  preview:
    if: github.event_name == "pull_request"
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Download Pages Artifact
        uses: actions/download-artifact@v4
        with:
          name: preview

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./html/

  deploy:
    if: github.event_name == "push"
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
